version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "miniconda3-3.12-24.9"

conda:
   environment: docs/environment.yml

mkdocs:
  configuration: mkdocs.yml

python:
   install:
     - method: pip
       path: .